BrewHow/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.ViewModels;
using BrewHow.Models;
using System.Threading.Tasks;

namespace BrewHow.Controllers
{
    public class StyleController : Controller
    {
        private readonly IStyleRepository _styleRepository;

        public StyleController(IStyleRepository styleRepository)
        {
            this._styleRepository = styleRepository;
        }

        public async Task<ActionResult> Index(int page = 0)
        {
            var styleList = Task.Factory.StartNew(() =>
            {
                var viewModel = new PagedResult<StyleEntity, StyleDisplayViewModel>(
                    _styleRepository.GetStyles(),
                    page,
                    ToDisplayModel);

                return viewModel;
            });

            return View(await styleList);
        }

        /// <summary>
        /// Converts a recipe entity into the display model sent
        /// to the view.
        /// </summary>
        /// <param name="entity">The entity to convert</param>
        /// <returns>A RecipeDisplayViewModel that represents the underlying domain entity</returns>
        private StyleDisplayViewModel ToDisplayModel(StyleEntity entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(
                    "entity",
                    "Cannot convert an entity to a view model when no entity is passed.");
            }

            return new StyleDisplayViewModel
            {
                StyleId = entity.StyleId,
                Name = entity.Name,
                Slug = entity.Slug,
                Category = entity.Category.ToString()
            };
        }

    }
}

BrewHow/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace BrewHow.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

BrewHow/Views/Shared/PagingPartial.cshtml
@model BrewHow.ViewModels.IPagedResult

<div id="pager">

@if (Model.Page > 0)
{
    @Html.RouteLink("<< Prev", new
    { 
        page = Model.Page - 1,
        controller = ViewContext.RouteData.Values["controller"],
        action = ViewContext.RouteData.Values["action"]
    },
    new
    {
        id = "paging-prev"
    });
}
<span>Page @(Model.Page + 1) of @Model.TotalPages</span>
@if (Model.Page + 1 != Model.TotalPages)
{
    @Html.RouteLink("Next >>", new
    {
        page = Model.Page + 1,
        controller = ViewContext.RouteData.Values["controller"],
        action = ViewContext.RouteData.Values["action"]
    },
    new
    {
        id = "paging-next"
    });
}
</div>

BrewHow/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        <header data-role="header">
            <a href="~/" 
                data-icon="home" 
                data-iconpos="notext">Home
            </a>
            <h1>BrewHow</h1>
            @Html.Partial("_LoginPartial")
            @if (Request.IsAuthenticated)
            {
                <nav data-role="navbar">
                    <ul>
                        <li>@Html.ActionLink(
                            "Recipes", 
                            "Index", 
                            "Recipe", 
                            new { area = "" }, 
                            @ViewContext.RouteData.Values["controller"].ToString().ToLower() == "recipe" ? new { @class="ui-btn-active" } : null)
                        </li> 
                        <li>@Html.ActionLink(
                            "My Library", 
                            "Index", 
                            "Library", 
                            new { area = "" }, 
                            @ViewContext.RouteData.Values["controller"].ToString().ToLower() == "library" ? new { @class="ui-btn-active" } : null)
                        </li>
                    </ul>
                </nav>
            }
        </header>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

        <footer data-role="footer" data-position="fixed">
            @Html.Partial("_ViewSwitcher")
        </footer>
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

BrewHow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - BrewHow</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("BrewHow", "Index", "Recipe", new { area = "" }, null)</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Recipes", "Index", "Recipe", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Styles", "Index", "Style", new { area = "" }, null)</li>
                            @if (Request.IsAuthenticated) {
                            <li>@Html.ActionLink("Library", "Index", "Library", new { area = "" }, null)</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - BrewHow and ASP.NET MVC 4 Mobile App Development</p>
                </div>
            </div>
            @Html.Partial("_ViewSwitcher")
        </footer>

        @Scripts.Render("~/bundles/jquery")
        <script src="~/Scripts/jquery.signalR-1.1.2.min.js" type="text/javascript"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>

        @RenderSection("scripts", required: false)
    </body>
</html>

BrewHow/Views/Shared/_LoginPartial.Mobile.cshtml
@if (Request.IsAuthenticated) {
    <a href="javascript:document.getElementById('logoutForm')
        .submit()" 
        data-role="button" 
        class="ui-btn-right">
        Log off
    </a>
    using (Html.BeginForm(
        "LogOff", 
        "Account", 
        new { area = "" },
        FormMethod.Post,
        new { id = "logoutForm" })) 
    {
        @Html.AntiForgeryToken()
    }
}
else
{
    @Html.ActionLink(
        "Log in", 
        "Login", 
        "Account", 
        new { area = "" }, 
        new { data_role="button", @class="ui-btn-right"});
}

BrewHow/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}