BrewHow/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using BrewHow.Validations;

namespace BrewHow.Models
{
    [MetadataType(typeof(RecipeValidationMetadata))]
    public class Recipe
    {
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public Style Style { get; set; }
        public float OriginalGravity { get; set; }
        public float FinalGravity { get; set; }
        public string GrainBill { get; set; }
        public string Instructions { get; set; }
        public string Slug { get; set; }

        public UserProfile Contributor { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }
    }
}

BrewHow/Areas/Review/Controllers/RecipeController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using BrewHow.Areas.Review.ViewModels;
using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;

namespace BrewHow.Areas.Review.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IReviewRepository _reviewRepository;
        private readonly IUserProfileEntityFactory _userProfileEntityFactory;

        public RecipeController(IReviewRepository reviewRepository,
            IUserProfileEntityFactory userProfileEntityFactory)
        {
            this._reviewRepository = reviewRepository;
            this._userProfileEntityFactory = userProfileEntityFactory;
        }

        public ActionResult Index(int id, string name)
        {
            var reviews = this
                ._reviewRepository
                .GetReviewsForRecipe(id);

            this.ViewBag.RecipeId = id;
            this.ViewBag.RecipeName = name;

            var reviewList = 
                reviews
                .AsEnumerable()
                .Select(s => ToListModel(s));

            if (Request.Browser.IsMobileDevice)
            {
                return View(reviewList);
            }

            return PartialView(reviewList);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(int id)
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, ReviewEditViewModel reviewEditViewModel)
        {
            try
            {
                var review = ToEntity(
                    id,
                    reviewEditViewModel
                );

                this
                    ._reviewRepository
                    .SaveReview(review);

                return this
                    .RedirectToAction(
                        "Details",
                        "Recipe",
                        new
                        {
                            id = id,
                            area = ""
                        });
            }
            catch
            {
                return View(reviewEditViewModel);
            }
        }

        private ReviewListViewModel ToListModel(ReviewEntity review)
        {
            return new ReviewListViewModel
            {
                Comment = review.Comment,
                Rating = review.Rating,
                Reviewer = review.Reviewer.UserName,
            };
        }

        private ReviewEntity ToEntity(int recipeId, ReviewEditViewModel viewModel)
        {
            return new ReviewEntity
            {
                RecipeId = recipeId,
                Comment = viewModel.Comment,
                Rating = viewModel.Rating,
                Reviewer = this._userProfileEntityFactory.Create()
            };
        }
    }
}

BrewHow/Controllers/LibraryController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.ViewModels;
using BrewHow.ViewModels.Mappers;
using WebMatrix.WebData;

namespace BrewHow.Controllers
{
    [Authorize]
    public class LibraryController : Controller
    {
        private readonly ILibraryRepository _libraryRepository;
        private readonly IUserProfileEntityFactory _userProfileEntityFactory;
        private readonly IRecipeDisplayViewModelMapper _displayModelMapper;

        public LibraryController(ILibraryRepository libraryRepository,
            IUserProfileEntityFactory userProfileEntityFactory,
            IRecipeDisplayViewModelMapper displayModelMapper)
        {
            this._libraryRepository = libraryRepository;
            this._userProfileEntityFactory = userProfileEntityFactory;
            this._displayModelMapper = displayModelMapper;
        }

        public async Task<ActionResult> Index(int page = 0)
        {
            var context = System.Web.HttpContext.Current;

            var recipeListTask = Task.Factory.StartNew(() =>
            {
                System.Web.HttpContext.Current = context;

                var recipesInLibrary = this
                    ._libraryRepository
                    .GetRecipesInLibrary(WebSecurity.CurrentUserId);

                var viewModel = new PagedResult<RecipeEntity, RecipeDisplayViewModel>(
                    recipesInLibrary,
                    page,
                    this._displayModelMapper.EntityToViewModel);

                return viewModel;
            });

            return View(await recipeListTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id)
        {
            int userId = WebSecurity.CurrentUserId;

            this
                ._libraryRepository
                .AddRecipeToLibrary(id, userId);

            return Json(new { result = "ok" } );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            int userId = WebSecurity.CurrentUserId;

            this
                ._libraryRepository
                .RemoveRecipeFromLibrary(id, userId);

            return Json(new { result = "ok" });
        }
    }
}

BrewHow/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.Models;
using BrewHow.ViewModels;
using BrewHow.ViewModels.Mappers;
using WebMatrix.WebData;

namespace BrewHow.Controllers
{
    public class RecipeController : Controller
    {
        // Create references to the repositories used 
        // to retrieve and persist entities used by 
        // the recipe controller.
        private readonly IRecipeRepository _recipeRepository;
        private readonly IStyleRepository _styleRepository;
        private readonly IUserProfileEntityFactory _userProfileEntityFactory;
        private readonly IRecipeDisplayViewModelMapper _displayViewModelMapper;
        private readonly IRecipeEditViewModelMapper _editViewModelMapper;

        public RecipeController(IRecipeRepository recipeRepository,
            IStyleRepository styleRepository,
            IUserProfileEntityFactory userProfileEntityFactory,
            IRecipeDisplayViewModelMapper displayViewModelMapper,
            IRecipeEditViewModelMapper editViewModelMapper)
            : base()
        {
            this._recipeRepository = recipeRepository;
            this._styleRepository = styleRepository;
            this._userProfileEntityFactory = userProfileEntityFactory;
            this._displayViewModelMapper = displayViewModelMapper;
            this._editViewModelMapper = editViewModelMapper;
        }

        // Respond to requests to ~/ with the list of
        // recipes in the system.
        public async Task<ActionResult> Index(int page = 0)
        {
            var recipeListTask = Task.Factory.StartNew(() =>
            {
                var recipes = _recipeRepository.GetRecipes();

                var viewModel = new PagedResult<RecipeEntity, RecipeDisplayViewModel>(
                    recipes,
                    page,
                    this._displayViewModelMapper.EntityToViewModel);

                return viewModel;
            });

            return View(await recipeListTask);
        }

        // Retrieve all of the recipes of a certain style.
        public async Task<ActionResult> Style(string style, int page = 0)
        {
            var recipeListTask = Task.Factory.StartNew(() =>
            {
                var recipesForStyle =
                    _recipeRepository.GetRecipesByStyleSlug(style);

                var viewModel = new PagedResult<RecipeEntity, RecipeDisplayViewModel>(
                    recipesForStyle,
                    page,
                    this._displayViewModelMapper.EntityToViewModel);

                return viewModel;
            });

            var styleEntity = _styleRepository.GetStyleBySlug(style);

            if (style != null)
            {
                ViewBag.Title = styleEntity.Name + " Recipes";
            }

            return View("Index", await recipeListTask);
        }

        // Retrieve the details of a recipe from the
        // recipe repository and send them on to the 
        // view used to display them to the user.
        public ActionResult Details(int id)
        {
            var recipe =
                this._recipeRepository.GetRecipe(id);

            var viewModel =
                this._displayViewModelMapper.EntityToViewModel(recipe);

            return View(viewModel);
        }

        // Return a view that allows the requestor
        // to create new recipes.
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = this
                ._editViewModelMapper
                .EntityToViewModel(null);

            return View(viewModel);
        }

        // Respond to the request to create a new 
        // recipe and return to the requestor the 
        // list of recipes if it's successful or
        // return them to the edit page on
        // failure.  ONLY respond to HTTP POST
        // requests.  The runtime will use model
        // binding to populate the recipe parameter.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeEditViewModel recipe)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var recipeEntity =
                        this._editViewModelMapper.ViewModelToEntity(recipe);

                    this._recipeRepository.Save(recipeEntity);

                    var context = Microsoft.AspNet.SignalR.
                        GlobalHost
                            .ConnectionManager
                            .GetHubContext<RecipeHub>();
                    context
                        .Clients
                        .All
                        .recipeAdded(
                            _displayViewModelMapper
                                .EntityToViewModel(recipeEntity)
                        );

                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }

            return View(recipe);
        }

        // Return a view that allows the requestor
        // to edit a specific recipe.  Return to the
        // view a ViewModel representing the recipe.
        [Authorize]
        public ActionResult Edit(int id)
        {
            var recipeToEdit = 
                this
                ._recipeRepository
                .GetRecipe(id);

            if (!CanEdit(recipeToEdit))
            {
                // Simply return the user to the detail view.
                // Not too worried about the throw.
                return RedirectToAction("Details", 
                    new 
                    { 
                        id = id 
                    });
            }

            var viewModel = this
                ._editViewModelMapper
                .EntityToViewModel(recipeToEdit);

            return View(viewModel);
        }

        // Respond to the request to edit an
        // existing recipe and return to the 
        // requestor the list of recipes if it's
        // successful or return them to the edit 
        // page on failure.  ONLY respond to HTTP 
        // POST requests.  The runtime will use 
        // model binding to populate the recipe 
        // parameter.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecipeEditViewModel recipe)
        {
            try
            {
                // Yes, it's a bit chatty, but we need to 
                // validate the entity from the database.
                var recipeEntity =
                    this._recipeRepository.GetRecipe(recipe.RecipeId);

                if (!CanEdit(recipeEntity))
                {
                    // Simply return the user to the detail view.
                    // Not too worried about the throw.
                    return RedirectToAction("Details", new { id = recipe.RecipeId });
                }

                var entityToSave = this
                    ._editViewModelMapper
                    .ViewModelToEntity(recipe);

                this._recipeRepository.Save(entityToSave);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private bool CanEdit(RecipeEntity entity)
        {
            if (Request.IsAuthenticated)
            {
                return WebSecurity.CurrentUserId == entity.Contributor.UserId;
            }

            return false;
        }
    }
}

BrewHow/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.ViewModels;
using BrewHow.Models;
using System.Threading.Tasks;

namespace BrewHow.Controllers
{
    public class StyleController : Controller
    {
        private readonly IStyleRepository _styleRepository;

        public StyleController(IStyleRepository styleRepository)
        {
            this._styleRepository = styleRepository;
        }

        public async Task<ActionResult> Index(int page = 0)
        {
            var styleList = Task.Factory.StartNew(() =>
            {
                var viewModel = new PagedResult<StyleEntity, StyleDisplayViewModel>(
                    _styleRepository.GetStyles(),
                    page,
                    ToDisplayModel);

                return viewModel;
            });

            return View(await styleList);
        }

        /// <summary>
        /// Converts a recipe entity into the display model sent
        /// to the view.
        /// </summary>
        /// <param name="entity">The entity to convert</param>
        /// <returns>A RecipeDisplayViewModel that represents the underlying domain entity</returns>
        private StyleDisplayViewModel ToDisplayModel(StyleEntity entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(
                    "entity",
                    "Cannot convert an entity to a view model when no entity is passed.");
            }

            return new StyleDisplayViewModel
            {
                StyleId = entity.StyleId,
                Name = entity.Name,
                Slug = entity.Slug,
                Category = entity.Category.ToString()
            };
        }

    }
}

BrewHow/Views/Recipe/Create.cshtml
@model BrewHow.ViewModels.RecipeEditViewModel

@{
    ViewBag.Title = "Create";
}

<article id="recipe-create">
<header>
    <h2>Contribute a Recipe</h2>
</header>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RecipeEditViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StyleId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.StyleId, Model.StyleList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OriginalGravity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OriginalGravity)
            @Html.ValidationMessageFor(model => model.OriginalGravity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FinalGravity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FinalGravity)
            @Html.ValidationMessageFor(model => model.FinalGravity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GrainBill)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GrainBill)
            @Html.ValidationMessageFor(model => model.GrainBill)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Instructions)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Instructions)
            @Html.ValidationMessageFor(model => model.Instructions)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
</article>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewHow/Views/Recipe/Details.Mobile.cshtml
@model BrewHow.ViewModels.RecipeDisplayViewModel

@{
    ViewBag.Title = "Details";
}

<article id="recipe-detail">
    <header>
    <h2><a href="#" data-role="button" data-icon="back" data-iconpos="notext" data-inline="true" onclick="javascript:history.go(-1)">Back</a> @Model.Name</h2>
    </header>
    <section>
        <header><strong>@Html.DisplayNameFor(model => model.PercentAlcoholByVolume)</strong></header>
        @Html.DisplayFor(model => model.PercentAlcoholByVolume)
    </section>
    <br>
    <section>
        <header><strong>@Html.DisplayNameFor(model => model.OriginalGravity)</strong></header>
        @Html.DisplayFor(model => model.OriginalGravity)
    </section>
        <br>
    <section>
        <header><strong>@Html.DisplayNameFor(model => model.FinalGravity)</strong></header>
        @Html.DisplayFor(model => model.FinalGravity)
        <br>
    </section>
        <br>
    <section>
        <header><strong>@Html.DisplayNameFor(model => model.GrainBill)</strong></header>
        @Html.DisplayFor(model => model.GrainBill)
        <br>
    </section>
        <br>
    <section>
        <header><strong>@Html.DisplayNameFor(model => model.Instructions)</strong></header>
        @Html.DisplayFor(model => model.Instructions)
    </section>
</article>
<br>
<div>
    @if (Request.IsAuthenticated) 
    { 
        @Html.ActionLink("Add to Library", "Create", "Library", 
        new { 
            id = Model.RecipeId 
        }, 
        new { 
            @class = "add-recipe", 
            data_id = Model.RecipeId,
            data_role = "button"
        })
        @Html.ActionLink("Edit Recipe", "Edit", new 
        { 
            id = Model.RecipeId, 
            slug = Model.Slug 
        }, 
        new { data_role = "button" })
    }
    @Html.ActionLink("View Reviews", "Index", new 
    { 
        area = "Review", 
        id = Model.RecipeId,
        name=Model.Name 
    }, 
    new { data_role = "button" })
    @if (Request.IsAuthenticated) 
    { 
        @Html.ActionLink("Add Review", "Create", new 
        { 
            area = "Review", 
            id = Model.RecipeId,
            name=Model.Name 
        }, 
        new { data_role = "button" }); 
    }
</div>

@Html.AntiForgeryToken()

@section scripts {
<script type="text/javascript">
    $(function () {
        $(".add-recipe").click(function(event) {
            event.preventDefault();
            $link = $(this);
            $.post($link.attr("href"),
                { __RequestVerificationToken: $("input[name=__RequestVerificationToken]").val() },
                function (response) {
                    if (response.result == "ok") {
                        $link.replaceWith("<span>Recipe Added</span>");
                    }
                }
            )
        });
    });
</script>

}

BrewHow/Views/Recipe/Details.cshtml
@model BrewHow.ViewModels.RecipeDisplayViewModel

@{
    ViewBag.Title = "Details";
}

<article id="recipe-detail">
<header>
    <h2>Recipe for @Model.Name</h2>
</header>
<fieldset>
    <legend>Recipe Details</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Style)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Style)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContributedBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContributedBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OriginalGravity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OriginalGravity)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FinalGravity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FinalGravity)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PercentAlcoholByVolume)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PercentAlcoholByVolume)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GrainBill)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GrainBill)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Instructions)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Instructions)
    </div>
</fieldset>
</article>
<p>
@if (Model.CanEdit) {
    @Html.ActionLink("Edit", "Edit", new { id=Model.RecipeId, slug = Model.Slug }) 
    @:|
}
    @Html.ActionLink("Back to List", "Index")
</p>
@{Html.RenderAction(
	"Index", 
	"Recipe", 
	new { 
		area = "Review", 
		id = Model.RecipeId, 
		slug = Model.Slug 
	});
}

BrewHow/Views/Recipe/Edit.Mobile.cshtml
@model BrewHow.ViewModels.RecipeEditViewModel

@{
    ViewBag.Title = "Edit";
}

<article id="recipe-edit">
<header>
    <h2>
    <a href="#" 
    data-role="button" 
    data-icon="back" 
    data-iconpos="notext" 
    data-inline="true"
    onclick="javascript:history.go(-1)">Back</a>
Edit: @Model.Name</h2>
</header>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="fieldcontain">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="fieldcontain">
            @Html.LabelFor(model => model.StyleId)
            @Html.DropDownListFor(model => model.StyleId, Model.StyleList)
        </div>
        <div class="fieldcontain">            
            @Html.LabelFor(model => model.OriginalGravity)
            @Html.EditorFor(model => model.OriginalGravity)
            @Html.ValidationMessageFor(model => model.OriginalGravity)
        </div>
        <div class="fieldcontain">
            @Html.LabelFor(model => model.FinalGravity)
            @Html.EditorFor(model => model.FinalGravity)
            @Html.ValidationMessageFor(model => model.FinalGravity)
        </div>
        <div class="fieldcontain">
            @Html.LabelFor(model => model.GrainBill)
            @Html.EditorFor(model => model.GrainBill)
            @Html.ValidationMessageFor(model => model.GrainBill)
        </div>
        <div class="fieldcontain">
            @Html.LabelFor(model => model.Instructions)
            @Html.EditorFor(model => model.Instructions)
            @Html.ValidationMessageFor(model => model.Instructions)
        </div>
        <p>
            <input type="submit" value="Save"/>
        </p>
    @Html.HiddenFor(model => model.RecipeId)
    @Html.HiddenFor(model => Model.Slug)
}
</article>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewHow/Views/Recipe/Edit.cshtml
@model BrewHow.ViewModels.RecipeEditViewModel

@{
    ViewBag.Title = "Edit";
}

<article id="recipe-edit">
<header>
    <h2>Editing @Model.Name</h2>
</header>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RecipeEditViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StyleId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.StyleId, Model.StyleList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OriginalGravity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OriginalGravity)
            @Html.ValidationMessageFor(model => model.OriginalGravity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FinalGravity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FinalGravity)
            @Html.ValidationMessageFor(model => model.FinalGravity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GrainBill)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GrainBill)
            @Html.ValidationMessageFor(model => model.GrainBill)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Instructions)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Instructions)
            @Html.ValidationMessageFor(model => model.Instructions)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
    @Html.HiddenFor(model => model.RecipeId)
    @Html.HiddenFor(model => Model.Slug)
}
</article>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewHow/Views/Recipe/Index.cshtml
@model BrewHow.ViewModels.ITypedPagedResult<BrewHow.ViewModels.RecipeDisplayViewModel>

@{
    ViewBag.Title = ViewBag.Title ?? "Recipes";
}

<h2>@ViewBag.Title</h2>

<p>
@if (Request.IsAuthenticated) {
    @Html.ActionLink("Create New", "Create")
}
</p>
<table id ="recipe-list">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Style)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].PercentAlcoholByVolume)
        </th>
        <th class="hide600">
            @Html.DisplayNameFor(model => model[0].OriginalGravity)
        </th>
        <th class="hide600">
            @Html.DisplayNameFor(model => model[0].FinalGravity)
        </th>
@if(Request.IsAuthenticated) {
        <th>
        </th>
}
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", new { id=item.RecipeId, slug=item.Slug })
        </td>
        <td>
            @Html.ActionLink(Html.DisplayFor(modelItem => item.Style).ToHtmlString(), "Style", "Recipe", new { style = item.StyleSlug }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PercentAlcoholByVolume)
        </td>
        <td class="hide600">
            @Html.DisplayFor(modelItem => item.OriginalGravity)
        </td>
        <td class="hide600">
            @Html.DisplayFor(modelItem => item.FinalGravity)
        </td>
@if (Request.IsAuthenticated) {
        <td>
            @Html.ActionLink("Add to Library", "Create", "Library", new { id = item.RecipeId }, new { @class = "add-recipe", data_id = @item.RecipeId })
        </td>
}
    </tr>
}

</table>

@{ Html.RenderPartial("PagingPartial", Model); }    

@Html.AntiForgeryToken()

@section scripts {
<script type="text/javascript">
    $(function () {
        $.connection.hub.start();

        var recipeHub = $.connection.recipeHub;
        recipeHub.client.recipeAdded = function (recipe) {
            var tr = $("#recipe-list").find('tbody')
                .append(
                    $('<tr>').css('background-color', '#ff0')
                        .append($('<td>')
                            .append($('<a>')
                            .attr('href', '/Recipe/Details/'
                                + recipe.RecipeId
                                + "/" + recipe.Slug)
                            .text(recipe.Name))
                        )
                        .append($('<td>')
                            .append($('<a>')
                            .attr('href', '/Recipe/'
                                +recipe.StyleSlug)
                            .text(recipe.Style))
                        )
                        .append($('<td>'
                            + recipe
                                .PercentAlcoholByVolume
                                .toFixed(2)
                            + '</td>'))
                        .append($('<td class="hide600">'
                            + recipe
                                .OriginalGravity
                                .toFixed(3)
                            + '</td>'))
                        .append($('<td class="hide600">'
                            + recipe
                                .FinalGravity
                                .toFixed(3)
                            + '</td>'))
@if (Request.IsAuthenticated) {
@:                        .append($('<td>'
@:                            + 'Add to Library'
@:                            + '</td>'))
}
                );
        }

        $(".add-recipe").click(function(event) {
            event.preventDefault();
            $link = $(this);
            $.post($link.attr("href"),
                { __RequestVerificationToken: $("input[name=__RequestVerificationToken]").val() },
                function (response) {
                    if (response.result == "ok") {
                        $link.replaceWith("<span>Recipe Added</span>");
                    }
                }
            )
        });
    });
</script>

}